spring.application.name=backend
server.port=${PORT:3000}
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Datasource URL, username and password will be injected programmatically 
# or via Spring Boot's automatic parsing if DATABASE_URL is standard.

